defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

markdown: kramdown

plugins:
  - jekyll-coffeescript

repository: junge-pfarre/junge-pfarre.github.io

host: 0.0.0.0

theme: jekyll-theme-slate
