defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

markdown: kramdown

plugins:
  - jekyll-coffeescript

repository: pfarrjugend-bnstst/pfarrjugend-bnstst.github.io

host: 0.0.0.0

theme: jekyll-theme-slate
